# Generated by Django 3.2.4 on 2021-06-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('capacity', models.IntegerField(default=0)),
                ('housepost', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhomes.admin')),
            ],
        ),
        migrations.CreateModel(
            name='HomeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HousePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameofhome', to='ourhomes.home')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhomes.homemanager')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='homemanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhomes.homemanager'),
        ),
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhomes.location'),
        ),
        migrations.AddField(
            model_name='home',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhomes.profile'),
        ),
    ]
