# Generated by Django 3.2.4 on 2021-06-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='home',
            name='homemanager',
        ),
        migrations.RemoveField(
            model_name='home',
            name='housepost',
        ),
        migrations.RemoveField(
            model_name='home',
            name='user',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhomes.admin')),
            ],
        ),
    ]
