# Generated by Django 3.2.4 on 2021-06-09 06:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0002_auto_20210609_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
