# Generated by Django 3.2.4 on 2021-06-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0012_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
