# Generated by Django 3.2.4 on 2021-06-09 22:08

from django.db import migrations, models
import ourhomes.models


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0014_auto_20210609_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='images',
            field=models.ImageField(null=True, upload_to=ourhomes.models.upload_image),
        ),
    ]
