# Generated by Django 3.2.4 on 2021-06-10 08:45

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0016_remove_home_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ourhomes.user')),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ourhomes.location'),
        ),
        migrations.AlterField(
            model_name='home',
            name='images',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ourhomes.user')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhomes.home')),
            ],
        ),
    ]
