# Generated by Django 3.2.4 on 2021-06-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0017_auto_20210610_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='GeneralAdmin',
        ),
    ]
