# Generated by Django 3.2.4 on 2021-06-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0018_rename_admin_generaladmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaladmin',
            name='location',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='home',
        ),
    ]
