# Generated by Django 3.2.4 on 2021-06-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0019_auto_20210610_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ourhomes.generaladmin'),
        ),
    ]
