# Generated by Django 3.2.4 on 2021-06-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourhomes', '0020_home_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='profile',
        ),
    ]
